name: Publish to NPM
on:
  workflow_dispatch:

  push:
    branches:
      - "main"
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          # registry-url: "https://registry.npmjs.org/"
      - name: Install dependencies and build 🔧
        run: npm install && npm run build
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          echo "Publishing to npm"
          npm publish
